# Generated by Django 3.0.4 on 2020-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
                ('product_vat_rate', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
