# Generated by Django 3.0.4 on 2020-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem2',
            name='created_at',
            field=models.DateField(default='2020-03-20'),
        ),
    ]
