# Generated by Django 3.0.4 on 2020-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem2_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem2',
            name='vendor_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
