# Generated by Django 3.0.4 on 2020-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem2_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem2',
            name='created_at',
            field=models.DateField(default='2020-03-21'),
        ),
    ]
