# Generated by Django 3.0.4 on 2020-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.FloatField(),
        ),
    ]
