# Generated by Django 3.0.4 on 2020-03-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='n_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
