# Generated by Django 3.0.4 on 2020-03-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200319_0837'),
        ('promotions', '0003_promotion_n_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='products.Product'),
        ),
    ]
