# Generated by Django 3.0.4 on 2020-03-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commission', to='vendors.Vendor')),
            ],
        ),
    ]
