# Generated by Django 3.0.4 on 2020-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20200318_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField()),
                ('orders', models.ManyToManyField(to='orders.Order')),
            ],
        ),
    ]
